### ISSUE TITLE
Support for building an extensions with input from different directories

### ISSUE THREAD

**Issue by ck-c8y** [Cumulocity-IoT/cumulocity-analytics-management#53]
Support for building an extensions with input from different directories in a single github repository, e.g.

content from:
1. `https://github.com/matj-sag/apama-analytics-builder-block-sdk/blob/python_block/samples/blocks/Python.mon`
2.  `https://github.com/matj-sag/apama-analytics-builder-block-sdk/tree/python_block/samples/plugins/Python`

Should result in the following list of files to be included in the extension:
``` 
        0  2025-02-25 13:36   files/
        0  2025-02-25 13:36   files/events/
        0  2025-02-25 13:36   files/venv/
     3743  2025-02-13 13:16   files/Python.mon
      188  2025-02-13 13:54   files/plugin.yaml
     1169  2025-02-13 14:35   files/pythonBlockPlugin.py
        0  2025-02-25 13:36   files/venv/lib/
        0  2025-02-25 13:36   files/venv/lib/python3.9/
        0  2025-02-25 13:36   files/venv/lib/python3.9/site-packages/
        0  2025-02-25 13:36   files/venv/lib/python3.9/site-packages/RestrictedPython/
     3201  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/Eval.py
     8089  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/Guards.py
     1866  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/Limits.py
     1137  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/PrintCollector.py
     3033  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/Utilities.py
     1862  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/__init__.py
      318  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/_compat.py
     6727  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/compile.py
    41419  2025-02-13 13:39   files/venv/lib/python3.9/site-packages/RestrictedPython/transformer.py
     1292  2025-02-25 13:36   files/events/python_extension_metadata.evt
     1725  2025-02-25 13:36   files/events/python_extension_messages.evt
```

**Comment by ck-c8y** [comment]
One solution could be to define a kind of deployment file containing the list of files to be included in the extension zip:

```
# This file contains a list of files (*.mon, .py, *.yaml any other files) to be included in a extension zip.
# The extension name should be the filename: extension_name 
# The file monitorList contains a list of lines with the following format:
#    <repository_id>:<path_in_repository> <path_file_to_copy_in_temp>


jct8tl:/events/ /events
jct8tl:/Python.mon /Python.mon
jct8tl:/plugin.yaml /plugin.yaml
jct8tl:/pythonBlockPlugin.py /pythonBlockPlugin.py
...
```

**Comment by ck-c8y** [comment]
A potential yaml structure could look like this:


```
# Extension Configuration

# Extension metadata
name: python_plugin_extension
description: Python plugin extension for Analytics Builder
version: 1.0.0

# Repository configuration
repository_id: my_github_repo

# Files to include in the extension
files:
  - source: /events/
    target: /events
    type: directory
    
  - source: /Python.mon
    target: /Python.mon
    type: file
    
  - source: /plugin.yaml
    target: /plugin.yaml
    type: file
    
  - source: /pythonBlockPlugin.py
    target: /pythonBlockPlugin.py
    type: file

# Build configuration
build:
  upload: true
  deploy: true
```
